name: Release Please
on:
  push:
    branches:
    - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Release Please
      id: release
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config-file: .release-please-config.json
        manifest-file: .release-please-manifest.json
        release-type: node

    # Mergear el PR directamente sin aprobación
    - name: Merge Release PR
      if: steps.release.outputs.pr != '' && steps.release.outputs.release_created != 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.number')
        gh pr merge $PR_NUMBER --squash --admin --repo ${{ github.repository }}
