name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          release-type: node

      # Si se creó un PR de release (NO un release), lo mergeamos automáticamente
      - name: Enable auto-merge for Release PR
        if: steps.release.outputs.pr != '' && steps.release.outputs.release_created != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.release.outputs.pr }} --auto --squash --repo ${{ github.repository }}

      # Opcional: Aprobar el PR automáticamente si tu repo requiere aprobaciones
      - name: Auto-approve Release PR
        if: steps.release.outputs.pr != '' && steps.release.outputs.release_created != 'true'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ fromJSON(steps.release.outputs.pr).number }}
